# Generated by Django 4.2.14 on 2024-11-26 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("encryptedfileupload", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="privatedocument",
            old_name="encrypted_original_file_name",
            new_name="encrypted_original_filename",
        ),
    ]
